eureka:
  client:
    serviceUrl:
          defaultZone: http://192.168.1.174:5000/eureka/
spring:
  application:
    name: feign-hystrix-consumer
server:
  port: 5006
feign:
  hystrix:
    enabled: true
